"""Static copy of the fraud policy (R1-R10, typologies, FinCEN) used when the GraphRAG index is unavailable."""

STATIC_POLICY_CHUNKS = [
    {"id": "RULE_R1", "category": "rule", "rule_id": "R1", "title": "Verify before you block on a weak signal", "approval_route": "auto", "content": "Rule R1. Verify before you block on a weak signal. If the case rests on a single signal (including a risk score alone) and your assessed fraud probability is below 0.70, recommend VERIFY_WITH_CUSTOMER or STEP_UP_AUTH before any block."},
    {"id": "RULE_R2", "category": "rule", "rule_id": "R2", "title": "Customer denies the transaction", "approval_route": "L1/L2", "content": "Rule R2. Customer denies the transaction. Recommend BLOCK_CARD and CREATE_CASE. Add FILE_REPORT if exposure exceeds $1,000 or the case connects to a shared device profile or another card's fraud."},
    {"id": "RULE_R3", "category": "rule", "rule_id": "R3", "title": "Customer confirms the transaction", "approval_route": "auto", "content": "Rule R3. Customer confirms the transaction. Recommend CLOSE_NO_FRAUD. Note the confirmation in the case file."},
    {"id": "RULE_R4", "category": "rule", "rule_id": "R4", "title": "No reply within 24 hours", "approval_route": "auto/L1", "content": "Rule R4. No reply within 24 hours. Recommend MONITOR_CARD (auto) and DECLINE_TRANSACTION (L1) for pending authorizations. Escalate if exposure exceeds $500."},
    {"id": "RULE_R5", "category": "rule", "rule_id": "R5", "title": "Card testing sequence", "approval_route": "L1/auto", "content": "Rule R5. Card testing. Three or more small online authorizations on one card within an hour, followed by a larger purchase: recommend DECLINE_TRANSACTION (L1) and STEP_UP_AUTH (auto). If a purchase over $100 has already cleared, recommend BLOCK_CARD."},
    {"id": "RULE_R6", "category": "rule", "rule_id": "R6", "title": "Shared origin and connected devices/regions", "approval_route": "auto/L2", "content": "Rule R6. Shared origin. When several cards show fraud from the same device profile, billing region (addr1), or recipient email in one window, recommend CREATE_CASE and FILE_REPORT (L2), and MONITOR_CONNECTED_CARDS (auto)."},
    {"id": "RULE_R7", "category": "rule", "rule_id": "R7", "title": "Disputed but legitimate recurring transaction", "approval_route": "auto", "content": "Rule R7. Disputed but legitimate. When the customer disputes a charge that matches their own recurring pattern, recommend CREATE_CASE, VERIFY_WITH_CUSTOMER, and WARN_CUSTOMER. Do not block."},
    {"id": "RULE_R8", "category": "rule", "rule_id": "R8", "title": "Escalate when uncertain and exposed", "approval_route": "auto", "content": "Rule R8. Escalate when uncertain and exposed. If the verdict is uncertain and exposure exceeds $500, or evidence conflicts, recommend ESCALATE_TO_ANALYST."},
    {"id": "RULE_R9", "category": "rule", "rule_id": "R9", "title": "Undocumented patterns", "approval_route": "auto/L2", "content": "Rule R9. Undocumented patterns. When activity fits none of the known patterns but shows coordinated abuse, recommend CREATE_CASE, FILE_REPORT (L2), and ESCALATE_TO_ANALYST."},
    {"id": "RULE_R10", "category": "rule", "rule_id": "R10", "title": "Never block all cards unless compromise confirmed", "approval_route": "L2", "content": "Rule R10. Never BLOCK_ALL_CARDS unless at least two of the customer's cards show confirmed fraud or credentials confirmed compromised."},
    {"id": "PATTERN_CARD_TESTING", "category": "pattern", "rule_id": "card_testing", "title": "Pattern 1: Card testing", "approval_route": "R5", "content": "A stolen card number is checked before use: three or more tiny online authorizations, often under $5, then a larger purchase. Confirmed by the sequence itself."},
    {"id": "PATTERN_CNP", "category": "pattern", "rule_id": "card_not_present_fraud", "title": "Pattern 2: Card-not-present fraud", "approval_route": "R1-R4", "content": "The number is used online without the physical card. Amounts and products that do not fit cardholder history in a burst of 2-4 in 48 hours."},
    {"id": "PATTERN_CNP_NEW_DEVICE", "category": "pattern", "rule_id": "card_not_present_new_device", "title": "Pattern 3: Card-not-present from a new device", "approval_route": "R1-R4", "content": "Online card-not-present fraud with identity record marking device as New for this account."},
    {"id": "PATTERN_OUT_OF_REGION", "category": "pattern", "rule_id": "out_of_region_use", "title": "Pattern 4: Out-of-region use", "approval_route": "R2-R3", "content": "Card-present purchases in a billing region the cardholder has no history in, while normal activity continues at home."},
    {"id": "PATTERN_ATO", "category": "pattern", "rule_id": "account_takeover", "title": "Pattern 5: Account takeover", "approval_route": "R10", "content": "Mixed-channel activity inconsistent with cardholder, often with device and match-flag anomalies."},
    {"id": "REG_FINCEN_SAR", "category": "regulatory", "rule_id": "FINCEN", "title": "FinCEN Suspicious Activity Report (SAR) Filing Requirements", "approval_route": "L2", "content": "A Suspicious Activity Report (FILE_REPORT) is a standalone regulatory filing sent outside the bank when confirmed or strongly suspected fraud exceeds $1,000 or involves connected rings."}
]
